### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/email-markup-consortium#1]
We need a code of conduct to establish guidelines for participation. We should establish this early, before we might ever need to point to it.

Let's gather some examples, see if there are open source templates we can look to, etc. But not be afraid to make it our own. A code of conduct we believe in is more important than ticking the box.

**Comment by Malvoz** [comment]
Relevant Github resource: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by husseinalhammad** [comment]
This may be helpful:
https://mozillascience.github.io/working-open-workshop/code_of_conduct/

**Comment by husseinalhammad** [comment]
Looking at the GitHub template, it seems good enough for us to use now. Two things stand out:

(1) The "contact method" may need to be defined there (or we can provide a link to it so we don't have to update the contact method in multiple places).

(2) Enforcement guidelines: do we keep them as is or define our own? Either way we need to make sure we're familiar with them
