### ISSUE TITLE
Requirements for a minimum viable website

### ISSUE THREAD

**Issue by dylanatsmith** [email-markup-consortium/email-markup-consortium#5]
In our [2021-08-31 meeting](https://github.com/email-standards/email-standards/blob/main/meeting-notes/2021-08-31.md#actions) we agreed to list things we need to include on a first version of a website. (This also acts as a proxy milestone for the group's early alignment.)

## Objective

A first version of our website should be shareable. We want visitors to understand our goals, any projects we're working on by its launch, how they can get involved or help, probably some contact info, etc.

## The basics
* Group name (discussion here: https://github.com/email-standards/email-standards/issues/4)
* Domain name to follow the above
* Mission statement (discussion here: https://github.com/email-standards/email-standards/issues/3)
* How to get involved
* Current members/contributors
* Contact name(s) and email address(es)

## Contributions wanted on this issue

1. Suggest other pieces of information we might want to include on a first pass at the website or beyond (we can always prioritise and iterate)
2. Link to other groups' websites and highlight what you like about them

**Comment by dylanatsmith** [comment]
We discussed creating a petition or similar, like [Overlay Fact Sheet](https://overlayfactsheet.com/) is having people sign in support of their mission.

This would add a stronger purpose behind linking to the site and make it more shareable. We do something similar for the Email Geeks Slack ["thanks" page](https://email.geeks.chat/thanks) after someone submits their application and see a [decent, steady take rate](https://twitter.com/search?q=I%20just%20signed%20up%20for%20the%20%23emailgeeks%20Slack%20group&src=typed_query&f=live) on the tweet prompt.

This might not be a V1 feature but I like the idea.

**Comment by dylanatsmith** [comment]
I also like what Chris Coyier does with the Do These Things section on [his website](https://chriscoyier.net). Very clear calls to action for anyone who might feel compelled and able to take any of them..

**Comment by M-J-Robbins** [comment]
Would it make sense to give some ideas of the projects we're going to be working on? To give people an idea of how we're going to try and achieve our goals.

Could just be a paragraph
_"We're going to be working on a number of projects bringing together email clients, email service providers and email developers to... "_

**Comment by dylanatsmith** [comment]
> Would it make sense to give some ideas of the projects we're going to be working on? To give people an idea of how we're going to try and achieve our goals.
> 
> 
> 
> Could just be a paragraph
> 
> _"We're going to be working on a number of projects bringing together email clients, email service providers and email developers to... "_ 

Yes, for sure. I don't think it's a blocker to not know specifics, but something like you wrote would work and as much info as we're able to provide is great.

**Comment by husseinalhammad** [comment]
I like how the [Open UI readme](https://github.com/openui/open-ui) clearly and concisely lists:

- What (mission)
- Who (audience)
- Why (problem)
- How (addressing the problem)

**Comment by M-J-Robbins** [comment]
I think it would be good to acknowledge previous efforts and maybe have something to suggest why we are optimistic that we can achieve something. As we saw in the initial slack discussion, there is some doubt into how much impact we can have.

Again not sure if this is needed for V1 but it could help with first impressions

**Comment by husseinalhammad** [comment]
+1 for acknowledging previous efforts. The fact that there were _multiple_ previous efforts is a good signal. It indicates the issues exist (and have existed for a long time) and have big enough negative impact for multiple groups to form. 

As for being optimistic, going back to the [Open UI readme](https://github.com/openui/open-ui):

> Timing - UI's have existed long enough to observe and codify a shared standard; the time is right.

I think the time is also right for us, particularly if the news about [Microsoft's One Outlook](https://www.windowscentral.com/project-monarch-outlook-web-universal-email-client-microsoft) are correct.

**Comment by Malvoz** [comment]
Do these qualify as previous efforts to be acknowledged?
- W3C Note - HTML Threading:
Conventions for use of HTML in email: https://www.w3.org/TR/1998/NOTE-HTMLThreading-0105
- W3C HTML Mail Workshop: https://www.w3.org/2007/05/html-mail/

**Comment by husseinalhammad** [comment]
Are we happy with this list as the requirements for an MVP site?
https://github.com/email-standards/email-standards/blob/main/meeting-notes/2021-09-21.md#5-website

If so, perhaps we can close this issue.

**Comment by dylanatsmith** [comment]
Closing this for now as a result of @Wilson110’s great input linked above.

I think there are good ideas here that we can iterate toward (who we are, what we are working on in practical terms, etc.) but we have what we need for a V1. Further ideas can be discussed on the website repo.

Note I've added a design mockup in https://github.com/email-markup-consortium/website/issues/1.
